# Numpy Basic

In [1]:
import numpy as np

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [2]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
zeros = np.zeros(1)
zeros

array([0.])

In [4]:
ones = np.ones([10, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

## arange : number generation

In [6]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [7]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [8]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [11]:
nums = [1, 2, 3, 4, 5]

In [12]:
nums[2:]

[3, 4, 5]

In [13]:
arr[1]

array([3, 4, 5])

In [14]:
arr[1][2]

5

In [15]:
arr[1, 2]

5

# Slicing

In [16]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [18]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

## Boolean Indexing

In [19]:
data = np.random.randn(3, 3)
data

array([[ 1.08929275,  0.0561335 ,  0.39275347],
       [-0.40503857, -1.61612064,  0.90492807],
       [ 0.4227448 ,  1.28102871,  2.14077645]])

In [23]:
data

array([[ 1.08929275,  0.0561335 ,  0.39275347],
       [-0.40503857, -1.61612064,  0.90492807],
       [ 0.4227448 ,  1.28102871,  2.14077645]])

In [24]:
data[data <= 0]

array([-0.40503857, -1.61612064])

In [25]:
data[data <= 0] = 1
data

array([[1.08929275, 0.0561335 , 0.39275347],
       [1.        , 1.        , 0.90492807],
       [0.4227448 , 1.28102871, 2.14077645]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [27]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [31]:
arr + np.array([1, 1, 1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [33]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [34]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [35]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [36]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [38]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr_2 = np.random.randint(2, size=9).reshape(3, 3)

In [43]:
arr

array([[[1, 1, 0],
        [1, 1, 1],
        [1, 0, 1]],

       [[1, 0, 1],
        [0, 1, 1],
        [1, 0, 0]],

       [[0, 1, 0],
        [1, 1, 1],
        [1, 1, 1]]])

In [39]:
arr.shape

(3, 3, 3)

In [44]:
arr_2

array([[0, 0, 0],
       [1, 0, 1],
       [0, 0, 1]])

In [40]:
arr_2.shape

(3, 3)

In [41]:
arr + arr_2

array([[[1, 1, 0],
        [2, 1, 2],
        [1, 0, 2]],

       [[1, 0, 1],
        [1, 1, 2],
        [1, 0, 1]],

       [[0, 1, 0],
        [2, 1, 2],
        [1, 1, 2]]])

In [42]:
arr * arr_2

array([[[0, 0, 0],
        [1, 0, 1],
        [0, 0, 1]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[0, 0, 0],
        [1, 0, 1],
        [0, 0, 1]]])

In [45]:
np.sum(arr)

19

In [46]:
np.sum(arr + arr_2)

28

In [48]:
np.max(arr + arr_2)

2

In [49]:
np.min(arr + arr_2)

0

In [50]:
arr + arr_2

array([[[1, 1, 0],
        [2, 1, 2],
        [1, 0, 2]],

       [[1, 0, 1],
        [1, 1, 2],
        [1, 0, 1]],

       [[0, 1, 0],
        [2, 1, 2],
        [1, 1, 2]]])

In [51]:
np.sum(arr + arr_2, 0)

array([[2, 2, 1],
       [5, 3, 6],
       [3, 1, 5]])

In [52]:
np.sum(arr + arr_2, -1)

array([[2, 5, 3],
       [2, 4, 2],
       [1, 5, 4]])

In [53]:
np.mean(arr)

0.7037037037037037

In [54]:
arr = np.array([1, 2, 5, 7, 7, 4, 5])
arr

array([1, 2, 5, 7, 7, 4, 5])

In [55]:
np.argmax(arr)

3

In [56]:
np.argmin(arr)

0

In [57]:
arr = np.array([ 3, 6, 4,1, 12, 3])

In [58]:
np.unique(arr)

array([ 1,  3,  4,  6, 12])

## data type

array의 dtype을 본다

In [65]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr.dtype

dtype('int32')

.astype()으로 datatype을 변환 가능

In [66]:
arr = arr.astype('float')

In [67]:
arr.dtype

dtype('float64')

In [68]:
arr

array([[1., 2., 3.],
       [1., 2., 3.]])

In [69]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype = np.uint8)
arr.dtype

dtype('uint8')

len(arr.shape)를 통해서 차원의 갯수를 확인할 수 있지만,
아래와 같이 ndim을 통해 차원 수를 return 가능

In [70]:
len(arr.shape)

2

size 확인

In [71]:
arr.size

6

## Reshape

In [72]:
arr.shape

(2, 3)

Reshape

In [75]:
arr = arr.reshape([1, 6])

In [76]:
arr.shape

(1, 6)

In [80]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [81]:
arr.shape

(2, 3)

In [82]:
arr.reshape([6]).shape

(6,)

In [83]:
arr.reshape(-1)

array([1, 2, 3, 1, 2, 3])

In [84]:
arr = arr.reshape(1, -1)
arr

array([[1, 2, 3, 1, 2, 3]])

random array 생성

In [85]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [86]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

3차원으로 늘리기

In [87]:
arr = arr.reshape(-1, 2, 1, 1)
arr.shape

(32, 2, 1, 1)

In [88]:
arr

array([[[[ 0.67732562]],

        [[-0.22992575]]],


       [[[-2.14687151]],

        [[-0.78646266]]],


       [[[ 0.97910155]],

        [[-1.19978068]]],


       [[[-0.81315118]],

        [[-0.04271251]]],


       [[[ 1.70850999]],

        [[ 0.96301119]]],


       [[[ 0.28310999]],

        [[-0.29295278]]],


       [[[ 0.47931767]],

        [[-0.88164674]]],


       [[[ 0.70507135]],

        [[-0.51184952]]],


       [[[ 0.36065512]],

        [[-1.23386802]]],


       [[[-0.06991052]],

        [[-0.36090727]]],


       [[[-2.090107  ]],

        [[-2.05356937]]],


       [[[-0.43634072]],

        [[-1.12558945]]],


       [[[-0.01485545]],

        [[ 0.18327702]]],


       [[[-1.02633319]],

        [[ 0.12417896]]],


       [[[-1.23320486]],

        [[-0.77052761]]],


       [[[ 0.57300642]],

        [[-0.43322353]]],


       [[[ 0.17883186]],

        [[-0.05052304]]],


       [[[ 0.18615974]],

        [[ 1.58578241]]],


       [[[-0.0737773 ]],

  

## Ravel

arr의 차원을 1차원으로 바꿔줌.

layer를 flatten시킬 때 사용

In [89]:
arr.shape

(32, 2, 1, 1)

In [90]:
arr = arr.ravel()
arr.shape

(64,)

## np.expand_dims()
안의 값은 유지하되 차원의 수를 늘리고 싶을 때 사용

In [91]:
arr.shape

(64,)

In [92]:
arr = np.expand_dims(arr, 0)
arr.shape

(1, 64)

In [93]:
arr = arr.ravel()

In [94]:
arr.shape

(64,)

In [95]:
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)