# 학습 목표

- TensorFlow 2.0 간단 사용법

In [2]:
import numpy as np
import tensorflow as tf

# Tensor 생성

- Python에서의 List 생성

In [4]:
[1, 2, 3]

[1, 2, 3]

In [5]:
[[1,2,3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

### Array 생성

- tuple이나 list 둘 다 np.array()로 씌어서 array를 만들 수 있음

In [6]:
arr = np.array([1,2,3])

In [7]:
arr.shape

(3,)

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
arr.shape

(2, 3)

### Tensor 생성

- tf.constant()
    - list -> Tensor

In [10]:
tf.constant([1, 2, 3])

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [11]:
a = tf.constant([1, 2, 3])
a.shape

TensorShape([3])

- tf.constant()
    - tuple -> Tensor

In [13]:
tf.constant(((1, 2, 3), (1, 2, 3)))

<tf.Tensor: id=2, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [14]:
a = tf.constant(((1, 2, 3), (1, 2, 3)))
a.shape

TensorShape([2, 3])

- tf.constant()
    - Array -> Tensor

In [15]:
arr = np.array([1, 2, 3])

In [17]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: id=5, shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

### Tensor에 담긴 정보 확인

- shape 확인

In [18]:
tensor.shape

TensorShape([3])

- data type 확인
    - 주의: Tensor 생성 할 때도 data type을 정해주지 않기 때문에 data type에 대한 혼동이 올 수 있음
    - Data Type에 따라 모델의 무게나 성능 차이에도 영향을 줄 수 있음

In [19]:
tensor.dtype

tf.int64

- data type 정의

In [22]:
tf.constant([1, 2, 3], dtype=tf.float32)

<tf.Tensor: id=7, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

- data type 변환
    - Numpy에서 astype()을 주었듯이, TensorFlow에서는 tf.cast를 사용

In [23]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: id=8, shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [25]:
arr = np.array([1, 2, 3], dtype = np.float32)
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [26]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: id=9, shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

- Tensor에서 Numpy 불러오기
    - .numpy()

In [27]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

- Tensor에서 Numpy 불러오기
    - np.array()

In [28]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

type()를 사용하여 numpy array로 변환된 것 확인

In [29]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [30]:
type(tensor.numpy())

numpy.ndarray

## 난수 생성

![](image/distribution.png)

- Normal Distribution은 중심 극한 이론(CLT: Central Limit Theorem)에 의한 연속적인 모양   
- Uniform Distribution은 중심 극한 이론(CLT: Central Limit Theorem)과는 무관하며 불연속적이며 일정한 분포

- numpy에서는 normal distribution을 기본적으로 생성
    - np.random.randn()

In [31]:
np.random.randn(9)

array([-1.27038561,  1.64430642, -1.08356308,  0.21912661,  1.61557878,
        0.00699617,  0.21909761,  0.0444886 ,  0.986893  ])

- tf.random.normal
    - TensorFlow에서 Normal Distribution

In [32]:
tf.random.normal([3, 3])

<tf.Tensor: id=15, shape=(3, 3), dtype=float32, numpy=
array([[-0.5687481 , -1.0925137 ,  1.3989962 ],
       [ 1.2593774 , -0.3876962 ,  0.30224353],
       [ 1.6916583 ,  0.05131084, -0.27574712]], dtype=float32)>

- tf.random.uniform
    - TensorFlow에서 Uniform Distribution

In [33]:
tf.random.uniform([4, 4])

<tf.Tensor: id=22, shape=(4, 4), dtype=float32, numpy=
array([[0.28966296, 0.44569564, 0.5628487 , 0.4086691 ],
       [0.44232357, 0.10266078, 0.22219992, 0.6168736 ],
       [0.3320682 , 0.04639995, 0.07132864, 0.68396354],
       [0.40978742, 0.10189402, 0.7871294 , 0.17280614]], dtype=float32)>